server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Faiz@1998
    
  jpa:
    hibernate:
      ddl-auto: update
    
    show-sql: true
    
  config:
    import: configserver:http://localhost:8084

#eureka:
#  instance:
#    prefer-ip-address: true
#    
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka